import type { Config } from 'tailwindcss';

const config: Config = {
    darkMode: ['class'],
    content: [
        './src/sections/**/*.{js,ts,jsx,tsx,mdx}',
        './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
        './src/components/**/*.{js,ts,jsx,tsx,mdx}',
        './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    theme: {
        fontFamily: {
            sans: `'Exo 2', 'sans-serif'`,
            mono: `'Montserrat', 'sans-serif'`,
            inter: `'Inter', 'sans-serif'`,
        },
        screens: {
            xs: '300px',
            sm: '375px',
            'sm-md': '601px',
            md: '768px',
            lg: '1200px',
            xl: '1440px',
        },
        extend: {
            boxShadow: {
                custom: '0px 0px 4px 0px #00000040',
            },
            container: {
                center: true,
                padding: {
                    DEFAULT: '20px',
                    lg: '80px',
                },
            },
            borderRadius: {
                lg: 'var(--radius)',
                md: 'calc(var(--radius) - 2px)',
                sm: 'calc(var(--radius) - 4px)',
            },
            colors: {
                abyssBlue: '#0f172a',
                abyssalBlue: '#020e1c',
                abstractBlue: '#123456',
                admiralBlue: '#232b45',
                angelWing: '#ffefef',
                apricotOrange: '#ff9f49',
                ashGray: '#5d5d5d',
                azureBlue: '#1ea1f1',
                basaltBlue: '#232a3a',
                berryRed: '#ce2e51',
                blazeRed: '#ff2e00',
                blushRed: '#f9536b',
                boldSlateBlue: '#232938',
                brightBlue: '#3b82f6',
                brightCoral: '#ff4c6b',
                brightElectricBlue: '#1755f6',
                bronzeGold: '#bb9b74',
                burntOrange: '#da481e',
                cadetGray: '#667085',
                charcoalBlue: '#1b202c',
                charcoalGray: '#1c1c1c',
                deepIndigo: '#282F4D',
                charcoalNavy: '#1b1e29',
                cherryRed: '#ff3b47',
                chiliRed: '#ea4335',
                classicSlateBlue: '#202437',
                cobaltNight: '#23263a',
                coolGray: '#d1d5db',
                coolSlate: '#374151',
                coralRed: '#ff5e62',
                crimsonBerry: '#ce2d52',
                crimsonRed: '#b0243f',
                cyanSky: '#0088cc',
                darkCrimsonRed: '#560100',
                darkSlateBlue: '#232733',
                deepForest: '#2c4b2a',
                deepMaroonRed: '#3b1a1a',
                deepNavy: '#151a28',
                deepNavyBlue: '#0e1628',
                deepOceanBlue: '#0e4273',
                deepRoyalBlue: '#1e3a8a',
                deepSeaNavy: '#1a2035',
                deepSlateBlue: '#1c2232',
                dimGray: '#8b8b8b',
                duskNavy: '#181d29',
                duskRosePink: '#8b2c4a',
                eclipseBlue: '#0b1019',
                electricBlue: '#1b4bff',
                electricRed: '#fb0005',
                fieryOrange: '#ff5e2f',
                fireRed: '#d43d1a',
                forestGreen: '#1a3b1a',
                goldenYellow: '#feca2a',
                googleBlue: '#4285f4',
                graphiteBlue: '#12141d',
                graphiteGray: '#23242a',
                graphiteNeutral: '#808080',
                graphiteSlateBlue: '#353b4b',
                grapefruitRed: '#ff7a7a',
                gunmetalBlue: '#1f293d',
                inkBlue: '#1e1e2d',
                inkSlateBlue: '#2c3242',
                intenseRed: '#f50000',
                ironSlateBlue: '#2c3142',
                kellyGreen: '#01891e',
                leafGreen: '#3ddc5a',
                lightSalmon: '#ff8a65',
                limeGreen: '#01ce34',
                marineBlue: '#233b6c',
                meadowGreen: '#4ecb71',
                merlotRed: '#b91c1c',
                midnightAlloy: '#181e2a',
                midnightBlue: '#1f2937',
                midnightInk: '#151b27',
                midnightNavy: '#0e1229',
                midnightSlateBlue: '#232631',
                mintGreen: '#d1f7c4',
                mistGray: '#e5e7eb',
                mistyLavenderBlue: '#a79cc7',
                mutedBlueGray: '#a1a1aa',
                mutedSlateGray: '#6a6d7c',
                neutralGray: '#a0a0a0',
                obsidianBlue: '#0d1117',
                oceanBlue: '#2563eb',
                onyxBlue: '#181c23',
                onyxGray: '#262527',
                paleBlue: '#e0e7ff',
                paleSlateBlue: '#b6b8c3',
                peachGold: '#ffa844',
                peachOrange: '#ffab43',
                periwinkleGray: '#b0b3c7',
                pewterGray: '#7d7e80',
                plumPink: '#af3189',
                poppyRed: '#ef4444',
                powderBlue: '#ebf0f7',
                primaryBlue: '#2977c9',

                regalIndigoBlue: '#3e3360',
                richSlateBlue: '#252d3d',
                roseRed: '#f04e4e',
                rosewater: '#f7c4c4',
                royalSlateBlue: '#2a3050',
                sapphireBlue: '#1480eb',
                sapphireDeep: '#1a1f4f',
                scarletRed: '#cf2f50',
                seafoamGreen: '#b6f5c2',
                shadowBlue: '#1e2538',
                shadowNavy: '#1a1f2b',
                shadowNavyBlue: '#181c27',
                shadowSlate: '#353744',
                silverStone: '#d9d9d9',
                skyBlue: '#5088ff',
                skyGlowBlue: '#2f88ff',
                slateBlack: '#181d27',
                slateBlue: '#353a45',
                softBlushRed: '#e07c7c',
                softCoral: '#ff6d68',
                softCoralRed: '#f87171',
                softGray: '#d0d5dd',
                softLavenderPink: '#b47fa4',
                softSlateBlue: '#a3b3c6',
                softSlateGray: '#9ca3af',
                springGreen: '#22c55e',
                steelBlue: '#111827',
                steelSlate: '#30384a',
                steelSlateBlue: '#2e3c5a',
                stoneGray: '#8f8f8f',
                stoneSlateBlue: '#2f3746',
                stormySlate: '#23283a',
                sunsetRed: '#ff5a4f',
                tangerineBlast: '#ff6a1a',
                terraRed: '#9f7a6f',
                terracottaOrange: '#e05a2b',
                twilightBlue: '#181a2a',
                twilightNavy: '#232738',
                vibrantOrange: '#ff6b00',
                vibrantRed: '#ff3b3b',
                vibrantSky: '#0090ff',
                vividBlue: '#3d70f5',
                vividPink: '#e4026e',
                vividSkyBlue: '#4e9df0',
                voidBlue: '#0a0911',
                warmOrange: '#f05921',
                wineRed: '#cd2a51',
                nocturneBlue: '#111827',
                grayLightTransparent: '#D9D9D959',
                background: 'hsl(var(--background))',
                foreground: 'hsl(var(--foreground))',
                card: {
                    DEFAULT: 'hsl(var(--card))',
                    foreground: 'hsl(var(--card-foreground))',
                },
                popover: {
                    DEFAULT: 'hsl(var(--popover))',
                    foreground: 'hsl(var(--popover-foreground))',
                },
                primary: {
                    DEFAULT: 'hsl(var(--primary))',
                    foreground: 'hsl(var(--primary-foreground))',
                },
                secondary: {
                    DEFAULT: 'hsl(var(--secondary))',
                    foreground: 'hsl(var(--secondary-foreground))',
                },
                muted: {
                    DEFAULT: 'hsl(var(--muted))',
                    foreground: 'hsl(var(--muted-foreground))',
                },
                accent: {
                    DEFAULT: 'hsl(var(--accent))',
                    foreground: 'hsl(var(--accent-foreground))',
                },
                destructive: {
                    DEFAULT: 'hsl(var(--destructive))',
                    foreground: 'hsl(var(--destructive-foreground))',
                },
                border: 'hsl(var(--border))',
                input: 'hsl(var(--input))',
                ring: 'hsl(var(--ring))',
                chart: {
                    '1': 'hsl(var(--chart-1))',
                    '2': 'hsl(var(--chart-2))',
                    '3': 'hsl(var(--chart-3))',
                    '4': 'hsl(var(--chart-4))',
                    '5': 'hsl(var(--chart-5))',
                },
            },
        },
    },
    plugins: [require('tailwindcss-animate')],
};

export default config;
