export interface JobPosting {
    roleName: string;
    status: "Open" | "Selection" | "Closed" | "Stale";
    mode: string;
    shortlisted: number;
    stipendAmount: string;
    applicants: number;
    postedDate: string;
};

export const jobPostings: JobPosting[] = [
    {
        roleName: "UI/UX Designer",
        status: "Open",
        mode: "Remote",
        shortlisted: 15,
        stipendAmount: "₹1000",
        applicants: 30,
        postedDate: "27/05/2024",
    },
    {
        roleName: "Software Developer",
        status: "Stale",
        mode: "Remote",
        shortlisted: 11,
        stipendAmount: "₹1000",
        applicants: 23,
        postedDate: "22/09/2024",
    },
    {
        roleName: "Data Analyst",
        status: "Open",
        mode: "On-site",
        shortlisted: 8,
        stipendAmount: "₹1200",
        applicants: 25,
        postedDate: "15/03/2024",
    },
    {
        roleName: "Frontend Developer",
        status: "Closed",
        mode: "Hybrid",
        shortlisted: 12,
        stipendAmount: "₹1500",
        applicants: 40,
        postedDate: "10/06/2024",
    },
    {
        roleName: "Backend Developer",
        status: "Open",
        mode: "Remote",
        shortlisted: 10,
        stipendAmount: "₹1300",
        applicants: 35,
        postedDate: "05/07/2024",
    },
    {
        roleName: "Product Manager",
        status: "Stale",
        mode: "On-site",
        shortlisted: 5,
        stipendAmount: "₹2000",
        applicants: 20,
        postedDate: "30/08/2024",
    },
    {
        roleName: "DevOps Engineer",
        status: "Open",
        mode: "Remote",
        shortlisted: 9,
        stipendAmount: "₹1400",
        applicants: 28,
        postedDate: "12/04/2024",
    },
    {
        roleName: "Graphic Designer",
        status: "Open",
        mode: "Hybrid",
        shortlisted: 7,
        stipendAmount: "₹900",
        applicants: 22,
        postedDate: "18/05/2024",
    },
    {
        roleName: "Marketing Specialist",
        status: "Closed",
        mode: "On-site",
        shortlisted: 6,
        stipendAmount: "₹1100",
        applicants: 15,
        postedDate: "25/06/2024",
    },
    {
        roleName: "QA Engineer",
        status: "Open",
        mode: "Remote",
        shortlisted: 13,
        stipendAmount: "₹1200",
        applicants: 32,
        postedDate: "03/09/2024",
    },
    {
        roleName: "Mobile App Developer",
        status: "Stale",
        mode: "Remote",
        shortlisted: 10,
        stipendAmount: "₹1600",
        applicants: 27,
        postedDate: "14/07/2024",
    },
    {
        roleName: "Content Writer",
        status: "Open",
        mode: "Remote",
        shortlisted: 4,
        stipendAmount: "₹800",
        applicants: 18,
        postedDate: "20/08/2024",
    },
    {
        roleName: "Cloud Architect",
        status: "Open",
        mode: "Hybrid",
        shortlisted: 11,
        stipendAmount: "₹1800",
        applicants: 30,
        postedDate: "09/05/2024",
    },
    {
        roleName: "Business Analyst",
        status: "Closed",
        mode: "On-site",
        shortlisted: 8,
        stipendAmount: "₹1300",
        applicants: 24,
        postedDate: "17/06/2024",
    },
    {
        roleName: "Cybersecurity Analyst",
        status: "Open",
        mode: "Remote",
        shortlisted: 9,
        stipendAmount: "₹1700",
        applicants: 29,
        postedDate: "28/04/2024",
    },
    {
        roleName: "AI/ML Engineer",
        status: "Stale",
        mode: "Remote",
        shortlisted: 12,
        stipendAmount: "₹2000",
        applicants: 33,
        postedDate: "01/09/2024",
    },
    {
        roleName: "Database Administrator",
        status: "Open",
        mode: "On-site",
        shortlisted: 7,
        stipendAmount: "₹1400",
        applicants: 21,
        postedDate: "11/07/2024",
    },
    {
        roleName: "SEO Specialist",
        status: "Open",
        mode: "Remote",
        shortlisted: 5,
        stipendAmount: "₹1000",
        applicants: 19,
        postedDate: "23/05/2024",
    },
    {
        roleName: "Full Stack Developer",
        status: "Closed",
        mode: "Hybrid",
        shortlisted: 14,
        stipendAmount: "₹1600",
        applicants: 38,
        postedDate: "07/06/2024",
    },
    {
        roleName: "Technical Writer",
        status: "Open",
        mode: "Remote",
        shortlisted: 3,
        stipendAmount: "₹900",
        applicants: 16,
        postedDate: "29/08/2024",
    },
    {
        roleName: "Network Engineer",
        status: "Stale",
        mode: "On-site",
        shortlisted: 8,
        stipendAmount: "₹1500",
        applicants: 26,
        postedDate: "13/04/2024",
    },
    {
        roleName: "Social Media Manager",
        status: "Open",
        mode: "Remote",
        shortlisted: 6,
        stipendAmount: "₹1100",
        applicants: 20,
        postedDate: "19/05/2024",
    },
    {
        roleName: "Game Developer",
        status: "Open",
        mode: "Hybrid",
        shortlisted: 10,
        stipendAmount: "₹1700",
        applicants: 31,
        postedDate: "26/06/2024",
    },
    {
        roleName: "IT Support Specialist",
        status: "Closed",
        mode: "On-site",
        shortlisted: 5,
        stipendAmount: "₹1000",
        applicants: 17,
        postedDate: "04/07/2024",
    },
    {
        roleName: "Data Scientist",
        status: "Open",
        mode: "Remote",
        shortlisted: 13,
        stipendAmount: "₹1900",
        applicants: 34,
        postedDate: "16/08/2024",
    },
    {
        roleName: "UX Researcher",
        status: "Stale",
        mode: "Remote",
        shortlisted: 7,
        stipendAmount: "₹1200",
        applicants: 22,
        postedDate: "08/05/2024",
    },
    {
        roleName: "Blockchain Developer",
        status: "Open",
        mode: "Remote",
        shortlisted: 9,
        stipendAmount: "₹2000",
        applicants: 28,
        postedDate: "21/06/2024",
    },
    {
        roleName: "Customer Success Manager",
        status: "Open",
        mode: "On-site",
        shortlisted: 4,
        stipendAmount: "₹1300",
        applicants: 15,
        postedDate: "02/09/2024",
    },
    {
        roleName: "Embedded Systems Engineer",
        status: "Closed",
        mode: "Hybrid",
        shortlisted: 11,
        stipendAmount: "₹1600",
        applicants: 30,
        postedDate: "10/04/2024",
    },
    {
        roleName: "Video Editor",
        status: "Open",
        mode: "Remote",
        shortlisted: 6,
        stipendAmount: "₹900",
        applicants: 18,
        postedDate: "27/07/2024",
    },
    {
        roleName: "Sales Manager",
        status: "Stale",
        mode: "On-site",
        shortlisted: 8,
        stipendAmount: "₹1400",
        applicants: 23,
        postedDate: "14/05/2024",
    },
    {
        roleName: "AR/VR Developer",
        status: "Open",
        mode: "Remote",
        shortlisted: 10,
        stipendAmount: "₹1800",
        applicants: 29,
        postedDate: "30/06/2024",
    },
    {
        roleName: "Copywriter",
        status: "Open",
        mode: "Remote",
        shortlisted: 5,
        stipendAmount: "₹800",
        applicants: 16,
        postedDate: "22/08/2024",
    },
    {
        roleName: "System Analyst",
        status: "Closed",
        mode: "On-site",
        shortlisted: 9,
        stipendAmount: "₹1500",
        applicants: 25,
        postedDate: "06/04/2024",
    },
    {
        roleName: "Motion Graphics Designer",
        status: "Open",
        mode: "Hybrid",
        shortlisted: 7,
        stipendAmount: "₹1100",
        applicants: 20,
        postedDate: "18/07/2024",
    },
    {
        roleName: "Scrum Master",
        status: "Stale",
        mode: "Remote",
        shortlisted: 6,
        stipendAmount: "₹1700",
        applicants: 22,
        postedDate: "25/05/2024",
    },
    {
        roleName: "E-commerce Specialist",
        status: "Open",
        mode: "Remote",
        shortlisted: 8,
        stipendAmount: "₹1200",
        applicants: 19,
        postedDate: "09/06/2024",
    },
    {
        roleName: "Hardware Engineer",
        status: "Open",
        mode: "On-site",
        shortlisted: 10,
        stipendAmount: "₹1600",
        applicants: 27,
        postedDate: "01/08/2024",
    },
    {
        roleName: "CRM Specialist",
        status: "Closed",
        mode: "Hybrid",
        shortlisted: 5,
        stipendAmount: "₹1300",
        applicants: 18,
        postedDate: "12/04/2024",
    },
    {
        roleName: "UI Developer",
        status: "Open",
        mode: "Remote",
        shortlisted: 12,
        stipendAmount: "₹1400",
        applicants: 31,
        postedDate: "28/05/2024",
    },
    {
        roleName: "Technical Support Engineer",
        status: "Stale",
        mode: "On-site",
        shortlisted: 7,
        stipendAmount: "₹1100",
        applicants: 20,
        postedDate: "15/07/2024",
    },
    {
        roleName: "Growth Hacker",
        status: "Open",
        mode: "Remote",
        shortlisted: 9,
        stipendAmount: "₹1500",
        applicants: 24,
        postedDate: "03/06/2024",
    },
    {
        roleName: "3D Animator",
        status: "Open",
        mode: "Hybrid",
        shortlisted: 6,
        stipendAmount: "₹1000",
        applicants: 17,
        postedDate: "19/08/2024",
    },
    {
        roleName: "IoT Developer",
        status: "Closed",
        mode: "Remote",
        shortlisted: 11,
        stipendAmount: "₹1800",
        applicants: 30,
        postedDate: "07/04/2024",
    },
    {
        roleName: "Digital Marketing Manager",
        status: "Open",
        mode: "Remote",
        shortlisted: 8,
        stipendAmount: "₹1200",
        applicants: 22,
        postedDate: "24/06/2024",
    },
    {
        roleName: "Site Reliability Engineer",
        status: "Stale",
        mode: "On-site",
        shortlisted: 10,
        stipendAmount: "₹1700",
        applicants: 28,
        postedDate: "11/05/2024",
    },
    {
        roleName: "Product Designer",
        status: "Open",
        mode: "Remote",
        shortlisted: 7,
        stipendAmount: "₹1300",
        applicants: 21,
        postedDate: "29/07/2024",
    },
    {
        roleName: "Operations Manager",
        status: "Open",
        mode: "On-site",
        shortlisted: 5,
        stipendAmount: "₹1400",
        applicants: 19,
        postedDate: "16/06/2024",
    },
    {
        roleName: "Data Engineer",
        status: "Closed",
        mode: "Hybrid",
        shortlisted: 12,
        stipendAmount: "₹1600",
        applicants: 32,
        postedDate: "04/05/2024",
    },
    {
        roleName: "Web Developer",
        status: "Open",
        mode: "Remote",
        shortlisted: 9,
        stipendAmount: "₹1100",
        applicants: 26,
        postedDate: "20/08/2024",
    },
];