import studentRegistrationT from '@/types/studentRegistration';
import companyRegistrationT from '@/types/companyRegistration';
import { JobPostingProgress } from '@/types/JobPostingProgress';
export const jobPostingProgress: JobPostingProgress = {
    file: 5,
    roleName: 15,
    skillsRequired: 15,
    openings: 10,
    type: 7,
    modeOfinteview: 5,
    workType: 5,
    city: 5,
    state: 5,
    country: 5,
    transportProvided: 3,
    questions: 15,
    rolesResp: 10,
    training: 5,
    expCertificate: 3,
    stipend: 3,
    bonus: 4,
    offer: 4,
    stipendCurrency: 1,
    bonusCurrency: 1,
    done: 0,
};

export const companyRegistration: companyRegistrationT = {
    city: 3,
    country: 3,
    state: 3,
    pinCode: 3,
    address: 3,
    fullName: 3,
    mail: 3,
    mobileNumber: 3,
    name: 3,
    size: 3,
    aboutCompany: 3,
    website: 3,
    linkedin: 3,
    gstDetail: 3,
    done: 0,
};

export const studentRegistration: studentRegistrationT = {
    photoUpload: 7,
    resumeUpload: 9,
    phoneNumber: 7,
    otpNumber: 7,
    fullName: 3,
    gender: 3,
    dob: 3,
    idProof: 3,
    mail: 3,
    linkedIn: 3,
    college: 3,
    course: 3,
    cgpa: 3,
    year: 3,
    skills: 9,
    github: 0,
    achievementTitle: 3,
    achievementToDate: 3,
    achievementTextField: 3,
    achievementDescription: 5,
    certificationTitle: 3,
    certIssuedBy: 1,
    certDate: 1,
    projToDate: 1,
    projFromDate: 1,
    projectDescription: 5,
    projectTitle:3,
    projectTextField: 3,
    achievmentFromDate: 1,
    done: 0,
};
