type studentRegistration = {
    photoUpload: number;
    resumeUpload: number;
    phoneNumber: number;
    otpNumber: number;
    fullName: number;
    gender: number;
    dob: number;
    idProof: number;
    mail: number;
    linkedIn: number;
    college: number;
    course: number;
    cgpa: number;
    year: number;
    skills: number;
    done: number;
    github: number;
    achievementTitle: number;
    achievementToDate: number;
    achievementTextField: number;
    certificationTitle: number;
    certIssuedBy: number;
    certDate: number;
    projToDate: number;
    projFromDate: number;
    projectTitle: number;
    projectDescription: number;
    projectTextField: number;
    achievementDescription: number;
    achievmentFromDate: number;
};
export default studentRegistration;
