import { RulesExamData } from '@/types/ExamTypes';
export const RuleData: RulesExamData = {
    exam: {
        name: 'Mathematics',
        subject: 'Algebra',
        questions: 30,
    },
    advice: [
        'Please ensure that the room has appropriate lighting.',
        'Please ensure that the camera is facing towards you.',
        'Please remain seated during the exam.',
        'Make sure that no one else can see your screen during the exam.',
        'Please refrain from using your mobile phone during the exam.',
    ],
    notSupported: [
        'Minimizing the browser',
        'Resizing the browser',
        'Open a new tab',
        'Open a new program',
        'Taking a screenshot',
        'Pressing Ctrl + C',
        'Pressing Ctrl+V',
        'Pressing Print Screen',
        'Pressing F12',
    ],
    agreement:
        'Have Read And Understood The Instructions. I Agree To Accept The Results Generated By This System.',
};
